import PaymentForm from "@/component/paymentform";
import { Elements } from "@stripe/react-stripe-js";
import { loadStripe } from "@stripe/stripe-js";
import Head from "next/head";
import Image from "next/image";

const stripePromise = loadStripe(process.env.NEXT_PUBLIC_API_KEY);

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Elements stripe={stripePromise}>
        <PaymentForm />
      </Elements>
    </div>
  );
}
