version: '3'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq

  doctor-service:
    build:
      context: ./doctor-service
    ports:
      - "3001:3000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672" 
      - "5672:5672"   
